---
version: "3.3"
services:
  redis:
    image: redis
    container_name: jerky-tts-bot-redis
    networks:
      - caching
    restart: "no"
  jerky-tts-bot-client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    container_name: jerky-tts-bot-client
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ".env:/app/.env"
      - "./config:/app/config"
      - "/tmp/jerky-tts-bot-api:/tmp/jerky-tts-bot-api"
      - "/tmp/jerky-tts-bot-discord:/tmp/jerky-tts-bot-discord"
    image: "blastbeng/jerky-tts-bot-client:1.0.0"
    restart: "no"
  jerky-tts-bot-telegram:
    build:
      context: ./telegram
      dockerfile: Dockerfile.telegram
    container_name: jerky-tts-bot-telegram
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ".env:/app/.env"
    image: "blastbeng/jerky-tts-bot-telegram:1.0.0"
    restart: "no"
  jerky-tts-bot-website:
    build:
      context: ./website
      dockerfile: Dockerfile.website
    container_name: jerky-tts-bot-website
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    ports:
      - '192.168.1.160:7391:80'
    image: "blastbeng/jerky-tts-bot-website:1.0.0"
    restart: "no"
    networks:
      - caching
networks:
  caching:
    driver: bridge
