---
version: "3.3"
services:
  discord-voicebot-api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    container_name: discord-voicebot-api
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    image: "blastbeng/discord-voicebot-api:1.0.0"
    restart: "no"
    volumes:
      - ".env:/app/.env"
      - "./config:/app/config"
      - "/tmp/scemo-pezzente-api:/tmp/scemo-pezzente-api"
      - "/dev/dri/card0:/dev/dri/card0"
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    entrypoint: ./entrypoint.sh
    #ports:
    #  - "5080:5080"
    networks:
      - caching
  discord-voicebot-battuteapi:
    container_name: discord-voicebot-battuteapi
    build:
      context: ./battuteAPI
      dockerfile: Dockerfile
    container_name: battuteapi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    image: "blastbeng/discord-voicebot-battuteapi:1.0.0"
    volumes:
      - ./config/battuteapi_data:/usr/src/app/data
    ports:
      - 3050:3050
    restart: "no"
  discord-voicebot-api-balancer:
    build:
      context: ./api
      dockerfile: Dockerfile.balancer
    container_name: discord-voicebot-api-balancer
    image: "blastbeng/discord-voicebot-api-balancer:1.0.0"
    ports:
      - "5080:5080"
    depends_on:
      - discord-voicebot-api
    volumes:
      - "/tmp/scemo-pezzente-api:/tmp/scemo-pezzente-api"
    restart: "no"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5080/utils/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 10
  redis:
    image: redis
    container_name: discord-voicebot-redis
    networks:
      - caching
    restart: "no"
  discord-voicebot-cron:
    container_name: discord-voicebot-cron
    build:
      context: ./cron
      dockerfile: Dockerfile.cron
    init: true
    volumes:
      - ./cron/crontab.txt:/etc/crontab
      - "/tmp/scemo-pezzente-discord:/discord-voicebot-client-tmpdir"
      - "/tmp/scemo-pezzente-api:/discord-voicebot-api-tmpdir"
  discord-voicebot-tor:
    container_name: discord-voicebot-tor
    ports:
      - '192.168.1.160:9058:9051'
    image: dockage/tor-privoxy
    restart: "no"
networks:
  caching:
    driver: bridge


