FROM nginx:alpine

WORKDIR /usr/share/nginx/html

COPY index.html .

RUN mkdir /usr/share/nginx/html/img
COPY img/*.* /usr/share/nginx/html/img

RUN mkdir /usr/share/nginx/html/css
COPY css/*.* /usr/share/nginx/html/css

RUN mkdir /usr/share/nginx/html/js
COPY js/*.* /usr/share/nginx/html/js
